### PR TITLE
OpenShift 4.13 support for PowerMax

### PR DESCRIPTION
**Pull request by shanmydell**
# Description
OpenShift 4.13 support for PowerMax
# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/724 |

# Checklist:

- [x] Have you run a grammar and spell checks against your submission?
- [x] Have you tested the changes locally?
- [x] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

### CODE REVIEW

**Review by santhoshhs10 — COMMENTED** [review]
Looks good to me

**Review by rajendraindukuri — APPROVED** [review]

**Review by gallacher — DISMISSED** [review]

**Review by boyamurthy — APPROVED** [review]

**Review by delldubey — APPROVED** [review]
lgtm

**Review by rajkumar-palani — APPROVED** [review]
lgtm

**Review by sharont58 — COMMENTED** [review]
No comments

**Pull request merged**
