### PR TITLE
Enabling light/dark mode menu

### PR DESCRIPTION
**Pull request by sidharth30060**
# Description
Enabling light/dark mode menu in the navbar

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/1476 |

# Checklist:

- [ ] Have you run a grammar and spell checks against your submission?
- [x] Have you tested the changes locally?
- [x] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

### CODE REVIEW

**Review by mgandharva — APPROVED** [review]
lgtm

**Review by shanmydell — CHANGES_REQUESTED** [review]
Hi @sidharth30060 , 
Please add the screenshots of the output of the testing and map GitHub issue to the pull request, Changes looks good to me

**Comment by sidharth30060** [comment]
**Light mode**
Screenshot 2024-09-16 152956
**Dark Mode**
Screenshot 2024-09-16 153007

**Review by shanmydell — APPROVED** [review]

**Comment by prablr79** [comment]
@sidharth30060  can you create github issue and associate with this PR ? and make sure this branch is up to date with base branch.  Thank you!

**Review by anandrajak1 — APPROVED** [review]

**Review by rajkumar-palani — APPROVED** [review]
lgtm

**Review by AronAtDell — APPROVED** [review]
Thanks! Looks good.

**Pull request merged**
