### PR TITLE
doc versions update

### PR DESCRIPTION
**Pull request by gilltaran**
# Description
Version Bump up for Operator

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| KRV-26067 |

# Checklist:

- [x] Have you run a grammar and spell checks against your submission?
- [x] Have you tested the changes locally?
- [x] Have you tested whether the hyperlinks are working properly?
- [x] Did you add the examples wherever applicable?
- [x] Have you added high-resolution images?

image
image
image
image
image

Screenshots After Auth 2.0.0 Addition
image
image

### CODE REVIEW

**Review by rajkumar-palani — CHANGES_REQUESTED** [review]
Hi @gilltaran - As mentioned in the checklist, can you please attach the local preview with the changes done? Thank You.

**Comment by gilltaran** [comment]
> Hi @gilltaran - As mentioned in the checklist, can you please attach the local preview with the changes done? Thank You.

@rajkumar-palani  I have attached the screenshots of local preview

**Review by rajkumar-palani — APPROVED** [review]
lgtm

**Comment by rajkumar-palani** [comment]
> > Hi @gilltaran - As mentioned in the checklist, can you please attach the local preview with the changes done? Thank You.
> 
> @rajkumar-palani I have attached the screenshots of local preview

Thank You

**Review by rajkumar-palani — CHANGES_REQUESTED** [review]
as discussed, please check and add auth 2.0 changes if it is needed in this PR. thanks.

**Comment by gilltaran** [comment]
> as discussed, please check and add auth 2.0 changes if it is needed in this PR. thanks.

@rajkumar-palani  Added the Auth 2.0.0 in the table

**Review by mgandharva — APPROVED** [review]
lgtm

**Review by rajkumar-palani — APPROVED** [review]
lgtm

**Review by ashleyvjoy — APPROVED** [review]

**Pull request merged**
