### PR TITLE
VGS version update

### PR DESCRIPTION
**Pull request by mgandharva**
# Description
Updated VGS version

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/1435 |

# Checklist:

- [x] Have you run a grammar and spell checks against your submission?
- [x] Have you tested the changes locally?
- [x] Have you tested whether the hyperlinks are working properly?
- [x] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

### CODE REVIEW

**Review by sharmilarama — CHANGES_REQUESTED** [review]
Please consolidate this effort to push all version updates together.

**Comment by mgandharva** [comment]
> Please consolidate this effort to push all version updates together.

This PR is only for the VGS version update, there are other stories for other version updates

**Review by harishp8889 — APPROVED** [review]

**Review by rajkumar-palani — APPROVED** [review]
lgtm. please respond to the other change request. Thanks.

**Comment by mgandharva** [comment]
> @mgandharva I understand the work is distributed, please coordinate to make these changes together so we can track all changes across the solution.

@sharmilarama I completely agree with your point, We will consider this improvement in the next release. Since we are in the FC milestone, I don't want this to be delayed.

**Comment by prablr79** [comment]
@mgandharva did you get a chance to work with across teams on the above request from @sharmilarama ?

**Comment by mgandharva** [comment]
> @mgandharva did you get a chance to work with across teams on the above request from @sharmilarama ?

@prablr79 We have communicated with the teams in SOS and POs across the different forums

**Comment by sharmilarama** [comment]
Some changes are consolidated here https://github.com/dell/csm-docs/pull/1282, please cover any remainders in this PR. Thanks!

**Pull request merged**
