### PR TITLE
FSGroup doc update

### PR DESCRIPTION
**Pull request by harishp8889**
# Description
Updated documentation for FSGroup policy

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/167 |

# Checklist:

- [x] Have you run grammar and spell checks against your submission?
- [x] Have you tested the changes locally?
- [ ] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

### CODE REVIEW

**Review by shanmydell — CHANGES_REQUESTED** [review]
Do we need this to be added to the features file? Release notes?

**Comment by harishp8889** [comment]
> Do we need this to be added to the features file? Release notes?

We have not explicitly implemented anything, This is available in Kubernetes and enabled by default from the 1.20 release, We are just providing an option to set the required `FSGroup policy` in the CSI driver - I don't see any need to mention it in either release notes or feature page

**Review by AronAtDell — APPROVED** [review]
This change is fairly straightforward! Thanks! All set!

**Comment by rsedlock1958** [comment]
I have reviewed this. No edits are required.

**Review by prablr79 — APPROVED** [review]

**Review by shanmydell — APPROVED** [review]
@randeepsharma will take care in common PowerScale PR

**Pull request merged**
