### PR TITLE
Added MKE 3.5.x support

### PR DESCRIPTION
**Pull request by shefali-malhotra**
# Description
- Added MKE 3.5.X in support matrix 
- Updated driver version in release notes

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/699|

# Checklist:

- [X] Have you run a grammar and spell checks against your submission?
- [X] Have you tested the changes locally?
- [ ] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

### CODE REVIEW

**Review by AronAtDell — APPROVED** [review]
Looks good! Thanks Team!

**Review by rajkumar-palani — APPROVED** [review]
lgtm

**Review by prablr79 — DISMISSED** [review]
Lgtm

**Review by rajkumar-palani — APPROVED** [review]
lgtm

**Review by prablr79 — APPROVED** [review]

**Pull request merged**
