### PR TITLE
CSI-Powerstore: Update Installation doc

### PR DESCRIPTION
**Pull request by satyakonduri**
# Description

- Update `Volume Snapshot Controller` section.
- Reorder 5  and 6 steps in `Install the Driver` section.
- Update Install Driver section in Operator installation.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| dell/csm#350 |

# Checklist:

- [x] Have you run a grammar and spell checks against your submission?
- [x] Have you tested the changes locally?
- [x] Have you tested whether the hyperlinks are working properly?
- [x] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

### CODE REVIEW

**Review by rsedlock1958 — COMMENTED** [review]
I have reviewed this. No edits are required.

**Review by spriya-m — APPROVED** [review]
Looks good to me.

**Review by shanmydell — APPROVED** [review]

**Comment by shanmydell** [comment]
@satyakonduri @spriya-m : Please sign the commits

**Review by adarsh-dell — APPROVED** [review]

**Comment by satyakonduri** [comment]
> @satyakonduri @spriya-m : Please sign the commits

Thank you @shanmydell 

Addressed.

**Review by spriya-m — APPROVED** [review]

**Review by shanmydell — APPROVED** [review]

**Pull request merged**
