### PR TITLE
Adding helm-charts-version flag 

### PR DESCRIPTION
**Pull request by boyamurthy**
Adding helm-charts-version flag for PowerMax and PowerStore

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/1218 |

# Checklist:

- [X] Have you run a grammar and spell checks against your submission?
- [ ] Have you tested the changes locally?
- [ ] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

### CODE REVIEW

**Review by delldubey — DISMISSED** [review]
lgtm

**Review by delldubey — DISMISSED** [review]
lgtm

**Review by suryagupta4 — APPROVED** [review]

**Comment by AkshaySainiDell** [comment]
@boyamurthy This change was introduced in CSM 1.8. Could you please update the docs for CSM 1.9 and 1.8 and as well ?

**Comment by boyamurthy** [comment]
> @boyamurthy This change was introduced in CSM 1.8. Could you please update the docs for CSM 1.9 and 1.8 and as well ?

hi @AkshaySainiDell  , added the changes to previous applicable releases, thank you .

**Review by shanmydell — APPROVED** [review]

**Pull request merged**
