### PR TITLE
Updated community qualification

### PR DESCRIPTION
**Pull request by rishabhatdell**
# Description
Added https://github.com/dell/csm/issues/1442 & https://github.com/dell/csm/issues/1441

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/1442 |
| https://github.com/dell/csm/issues/1441 |
# Checklist:

- [ ] Have you run a grammar and spell checks against your submission?
- [ ] Have you tested the changes locally?
- [x] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

### CODE REVIEW

**Review by shanmydell — APPROVED** [review]
Please update RHCOS, rest of the changes looks good to me

**Review by coulof — APPROVED** [review]
LGTM

**Comment by coulof** [comment]
@shanmydell shouldn't we merge it in release-v1.11.0 so it is visible to the current version ?

**Comment by rishabhatdell** [comment]
> @shanmydell shouldn't we merge it in release-v1.11.0 so it is visible to the current version ?

this PR is for that: https://github.com/dell/csm-docs/pull/1239

**Pull request merged**
