### PR TITLE
Restructured deployment documentation

### PR DESCRIPTION
**Pull request by gallacher**
# Description
Updates made to documentation to not recommend the CSM Installer as the recommended way to deploy CSM.  Restructured the documentation accordingly and added section in troubleshooting guide to describe how to upgrade if the CSM Installer was used to deploy CSM 1.0.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [x] Have you run a grammar and spell checks against your submission?
- [x] Have you tested the changes locally?
- [x] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

### CODE REVIEW

**Comment by tdawe** [comment]
Should this target the release-1.1 branch?

**Comment by gallacher** [comment]
> 

Yes! Thank you for noticing that.

**Comment by gallacher** [comment]
> Should this target the release-1.1 branch?

Yes.  Thanks @tdawe for noticing that.

**Comment by shanmydell** [comment]
@gallacher : Could you rebase the PR

**Pull request closed without merging**
