### PR TITLE
Simplify wording

### PR DESCRIPTION
**Pull request by coulof**
# Description
Simplify wording and add tab to ease the reading

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/1444|

# Checklist:

- [ ] Have you run a grammar and spell checks against your submission?
- [x] Have you tested the changes locally?
- [ ] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

### CODE REVIEW

**Comment by shanmydell** [comment]
@coulof : Please raise another PR for main, thanks

**Review by shanmydell — APPROVED** [review]

**Comment by shanmydell** [comment]
Also please add GitHub issue linked to it

**Comment by coulof** [comment]
@shanmydell, can't we `git checkout main ; git merge release-1.11.0` ?

I don't want to duplicate modification while we have git for it.

There was no ticket it is a suggestion coming from the community.

**Comment by shanmydell** [comment]
> @shanmydell, can't we `git checkout main ; git merge release-1.11.0` ?
> 
> I don't want to duplicate modification while we have git for it.
> 
> There was no ticket it is a suggestion coming from the community.

@coulof : We wanted to get away from that model, as it is removing important information as part of resolving merge conflicts, if it is very important it can goto the release branch or it can be part of the main and be part of 1.12, right now the website is hosted from release 1.11 branch

**Comment by coulof** [comment]
@shanmydell ticket created : https://github.com/dell/csm/issues/1444 & PR against `main` created : https://github.com/dell/csm-docs/pull/1240

**Pull request closed without merging**
