### PR TITLE
Release 1.10.1

### PR DESCRIPTION
**Pull request by adarsh-dell**
# Description
A few sentences describing the overall goals of the pull request's commits.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/1217|

# Checklist:

- [x] Have you run a grammar and spell checks against your submission?
- [ ] Have you tested the changes locally?
- [ ] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

### CODE REVIEW

**Review by shanmydell — CHANGES_REQUESTED** [review]
@adarsh-dell : Did we updated config.toml and installation wizard files?

**Comment by adarsh-dell** [comment]
> @adarsh-dell : Did we updated config.toml and installation wizard files?

DONE @shanmydell

**Review by shanmydell — APPROVED** [review]
LGTM

**Review by boyamurthy — APPROVED** [review]

**Review by AkshaySainiDell — APPROVED** [review]
LGTM

**Pull request merged**
