### PR TITLE
Update csi operator 1.11.0 release notes

### PR DESCRIPTION
**Pull request by samihan-dell**
# Description
- Updated the release notes for operator

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/583 |

# Checklist:

- [X] Have you run a grammar and spell checks against your submission?
- [X] Have you tested the changes locally?
- [X] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

### CODE REVIEW

**Review by rajkumar-palani — APPROVED** [review]
lgtm

**Review by rsedlock1958 — DISMISSED** [review]
I have reviewed this. No edits are required.

**Review by prablr79 — APPROVED** [review]
Lgtm

**Review by rensyct — APPROVED** [review]

**Review by rajkumar-palani — APPROVED** [review]
lgtm

**Pull request merged**
