### PR TITLE
Documentation changes  for csm-operator

### PR DESCRIPTION
**Pull request by karthikk92**
# Description
Documentation changes  for csm-operator

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/583 |

# Checklist:

- [x] Have you run a grammar and spell checks against your submission?
- [ ] Have you tested the changes locally?
- [x] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

### CODE REVIEW

**Review by rajkumar-palani — CHANGES_REQUESTED** [review]
Can you please check the Checklist and update?

**Review by rsedlock1958 — APPROVED** [review]
No edits required.

**Review by bjiang27 — DISMISSED** [review]

**Review by rensyct — APPROVED** [review]

**Review by rajendraindukuri — DISMISSED** [review]

**Review by bjiang27 — DISMISSED** [review]

**Review by rajkumar-palani — DISMISSED** [review]
lgtm

**Review by rajendraindukuri — APPROVED** [review]

**Review by rajkumar-palani — APPROVED** [review]
lgtm

**Pull request merged**
