### PR TITLE
Update Observability with Authorization helm deployment and other minor fixes

### PR DESCRIPTION
**Pull request by atye**
# Description

CSM-Authorization is deprecating sidecar injection so the `sidecarproxyaddr` in the configuration is being removed. This also notes the necessary `mountEndpoint` field in the csi-isilon secret if CSM-Authorization is enabled and fixes some misleading documentation.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/112 |

# Checklist:

- [x] Have you run a grammar and spell checks against your submission?
- [x] Have you tested the changes locally?
- [x] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

### CODE REVIEW

**Comment by tdawe** [comment]
Should this target a release branch instead of main?

**Comment by tdawe** [comment]
Since injection is being removed, the documentation also contains other references to using `inject`. Can those references be deleted as part of this PR? Or will there be another PR?

**Comment by atye** [comment]
> Should this target a release branch instead of main?

I think you're right. This PR targets release-1.2 now.

**Comment by atye** [comment]
> Since injection is being removed, the documentation also contains other references to using `inject`. Can those references be deleted as part of this PR? Or will there be another PR?

They can be deleted on this PR. Working on that.

**Comment by atye** [comment]
> > Since injection is being removed, the documentation also contains other references to using `inject`. Can those references be deleted as part of this PR? Or will there be another PR?
> 
> They can be deleted on this PR. Working on that.

Pushed changes removing references of injection. A good chunk of troubleshooting was removed.

**Review by alikdell — APPROVED** [review]

**Review by hoppea2 — APPROVED** [review]

**Review by tdawe — APPROVED** [review]

**Pull request merged**
