### PR TITLE
Moved the Installation wizard code

### PR DESCRIPTION
**Pull request by niranjan-n1**
# Description
 Moved the CSM Installation Wizard code to dell/csm-docs repository from the private repository.
# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| dell/csm#591 |

# Checklist:

- [x] Have you run a grammar and spell checks against your submission?
- [x] Have you tested the changes locally?
- [x] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

### CODE REVIEW

**Comment by rajkumar-palani** [comment]
@niranjan-n1 - Does the peer review completed for the changes? can you please get an approval from your team members?

**Comment by niranjan-n1** [comment]
> @niranjan-n1 - Does the peer review completed for the changes? can you please get an approval from your team members?

 @rajkumar-palani. Yes, these changes have been reviewed and is from the main branch.

**Comment by satyakonduri** [comment]
Copyright headers are missing for a few files. Please add wherever possible.
Thank You.!

**Review by chaganti-rajitha — APPROVED** [review]

**Comment by niranjan-n1** [comment]
> Copyright headers are missing for a few files. Please add wherever possible. Thank You.!

@satyakonduri  Added. Thanks

**Review by chaganti-rajitha — APPROVED** [review]

**Review by chaganti-rajitha — APPROVED** [review]

**Review by spriya-m — APPROVED** [review]

**Review by shanmydell — APPROVED** [review]

**Pull request merged**
