### PR TITLE
Fix interactive form, no tag menu, add images in template

### PR DESCRIPTION
**Pull request by coulof**
# Description
Previous version was displaying the entire form, now fixed in the javascript

Per request, add all `images` tags to the template

The tags on the left menu prevent to launch the `Interactive Tutorial`

# GitHub Issues

- https://github.com/dell/csm/issues/1055
- https://github.com/dell/csm/issues/1012

# Checklist:

- [ ] Have you run a grammar and spell checks against your submission?
- [x] Have you tested the changes locally?
- [ ] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

### CODE REVIEW

**Comment by shanmydell** [comment]
@coulof : Still checks are not passing, please look int the same

**Review by mareksuski-dell — APPROVED** [review]
LGTM

**Review by gallacher — APPROVED** [review]
LGTM

**Review by gallacher — DISMISSED** [review]
Fix failing checks

**Review by shanmydell — APPROVED** [review]

**Review by suryagupta4 — APPROVED** [review]

**Pull request merged**
