### PR TITLE
Add tabs to improve readability

### PR DESCRIPTION
**Pull request by coulof**
# Description
Add tabs to improve readability for PowerStore.

Partially solves the issue as it has to be done for others too.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| [1444](https://github.com/dell/csm/issues/1444) |
Relates to PR https://github.com/dell/csm-docs/pull/1237
# Checklist:

- [ ] Have you run a grammar and spell checks against your submission?
- [x] Have you tested the changes locally?
- [ ] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

### CODE REVIEW

**Comment by sharmilarama** [comment]
Is there a plan to update this everywhere else?

**Review by gallacher — CHANGES_REQUESTED** [review]
Please ensure this PR addresses these changes holistically across all of the documentation.  Thanks.

**Comment by coulof** [comment]
@gallacher, IMHO it makes no sense to do the same for Unity, PowerScale and PowerFlex.

I let you decide to close without or without merging the PR.

**Comment by anandrajak1** [comment]
This will be handled as part of CSM 1.13 doc restructure

**Pull request closed without merging**
