### PR TITLE
Operator Minimal CR feature: Documentation

### PR DESCRIPTION
**Pull request by ashleyvjoy**
# Description
Documentation to deploy CSM using Operator minimal CR files

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| (https://github.com/dell/csm/issues/1449) |

# Checklist:

- [x] Have you run a grammar and spell checks against your submission?
- [x] Have you tested the changes locally?
- [x] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [x] Have you added high-resolution images?
image
preview-pflex
preview-pmax
preview-pstore

### CODE REVIEW

**Review by rajkumar-palani — CHANGES_REQUESTED** [review]
can you please attach the local preview as mentioned in the checklist?

**Comment by ashleyvjoy** [comment]
> can you please attach the local preview as mentioned in the checklist?

@rajkumar-palani Sure. I've added the images as mentioned in the checklist. Local preview is hosted in my dev VM. We do not mention IPs in public facing repos

**Comment by rajkumar-palani** [comment]
> > can you please attach the local preview as mentioned in the checklist?
> 
> @rajkumar-palani Sure. I've added the images as mentioned in the checklist. Local preview is hosted in my dev VM. We do not mention IPs in public facing repos. I will ping the preview link to you over slack

Thank You.

**Review by rajkumar-palani — APPROVED** [review]
lgtm

**Review by harishp8889 — APPROVED** [review]

**Pull request merged**
