### PR TITLE
Updates for csm-operator 1.4.4 release

### PR DESCRIPTION
**Pull request by jooseppi-luna**
# Description
Add two bugs and update versions for csm-operator v1.4.4 release.
# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/1189|
|https://github.com/dell/csm/issues/1190|

# Checklist:

- [x] Have you run a grammar and spell checks against your submission?
- [x] Have you tested the changes locally?
- [x] Have you tested whether the hyperlinks are working properly?
- [x] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

### CODE REVIEW

**Review by boyamurthy — APPROVED** [review]

**Review by delldubey — APPROVED** [review]
looks good

**Review by shanmydell — CHANGES_REQUESTED** [review]
This should go to v1 version now, requesting to redo all the changes

**Comment by jooseppi-luna** [comment]
1.10 was released, so these changes need to go in v1 folder now -- @delldubey took care of this in another PR

**Review by shanmydell — CHANGES_REQUESTED** [review]
changes should go to v1

**Review by shanmydell — APPROVED** [review]

**Pull request merged**
