### PR TITLE
Pflex 4.0 docs

### PR DESCRIPTION
**Pull request by JacobGros**
# Description
Add a short clarifier for Pflex 4.0 systems 
# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|  https://github.com/dell/csm/issues/491 |

# Checklist:

- [x] Have you run a grammar and spell checks against your submission?
- [ ] Have you tested the changes locally?
- [ ] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

### CODE REVIEW

**Review by mbasha-dell — APPROVED** [review]

**Review by rsedlock1958 — COMMENTED** [review]
I have reviewed this. No edits are required.

**Review by bharathsreekanth — COMMENTED** [review]
Don't we need to update support matrix as well to indicate support for 4.0?

**Review by bharathsreekanth — APPROVED** [review]
Another caveat - We are not supporting all modules with 4.0, only observability. Is there any place we can capture that?

**Comment by JacobGros** [comment]
> Another caveat - We are not supporting all modules with 4.0, only observability. Is there any place we can capture that?

Modules have their own supported array sections, like [this](https://github.com/dell/csm-docs/blob/main/content/docs/observability/_index.md#supported-storage-platforms)
By default, no module claims support for 4.0, but after obs team runs their quals, they can update their section.

**Review by mjsdell — APPROVED** [review]

**Review by rsedlock1958 — COMMENTED** [review]
I have reviewed this. No edits are required.

**Pull request merged**
