### PR TITLE
Update Application Mobility documentation to refer to APEX Navigator for Kubernetes

### PR DESCRIPTION
**Pull request by tdawe**
# Description
Direct US-based customers to use APEX Navigator for Kubernetes for Application Mobility instead of requesting a trial license.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/1221 |

# Checklist:

- [ ] Have you run a grammar and spell checks against your submission?
- [x] Have you tested the changes locally?
- [x] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

### CODE REVIEW

**Review by shanmydell — CHANGES_REQUESTED** [review]
https://github.com/dell/csm-docs/blob/035722324bd43cdf4b4a1dde13e426431e0e85f1/content/docs/deployment/_index.md?plain=1#L63

Please modify the above file.

**Comment by shanmydell** [comment]
@tdawe : https://github.com/dell/csm-docs/blob/035722324bd43cdf4b4a1dde13e426431e0e85f1/content/docs/deployment/csmoperator/release/_index.md?plain=1#L34 - Should we consider removing application mobility here?

**Comment by tdawe** [comment]
> https://github.com/dell/csm-docs/blob/035722324bd43cdf4b4a1dde13e426431e0e85f1/content/docs/deployment/_index.md?plain=1#L63
> 
> Please modify the above file.

That section has been removed

**Comment by tdawe** [comment]
> @tdawe :
> 
> https://github.com/dell/csm-docs/blob/035722324bd43cdf4b4a1dde13e426431e0e85f1/content/docs/deployment/csmoperator/release/_index.md?plain=1#L34
> 
> - Should we consider removing application mobility here?

Yes, that mention of application-mobility has been removed

**Review by shanmydell — APPROVED** [review]

**Comment by shanmydell** [comment]
@tdawe : Please get the necessary approvals and merge the change, thanks

**Review by AkshaySainiDell — APPROVED** [review]

**Review by suryagupta4 — APPROVED** [review]

**Pull request merged**
