### PR TITLE
Update documentation to enable users to clone v2.0.0 of drivers directly

### PR DESCRIPTION
**Pull request by francis-nijay**
# Description
As part of true open source model, CSI driver documentation will now enable to fetch v2.0.0 of the drivers directly during clone

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| Issue 93 |

# Checklist:

- [x] Have you run a grammar and spell checks against your submission?
- [x] Have you tested the changes locally?
- [x] Have you tested whether the hyperlinks are working properly?
- [x] Did you add the examples wherever applicable?
- [x] Have you added high-resolution images?

### CODE REVIEW

**Review by shanmydell — CHANGES_REQUESTED** [review]
https://dell.github.io/csm-docs/docs/csidriver/upgradation/drivers/isilon/ @francis-nijay Please update the upgrade pages as well

**Comment by francis-nijay** [comment]
> https://dell.github.io/csm-docs/docs/csidriver/upgradation/drivers/isilon/ @francis-nijay Please update the upgrade pages as well

Added change to upgradation pages as well.

**Review by shanmydell — CHANGES_REQUESTED** [review]
https://github.com/dell/csm-docs/blob/main/content/docs/csidriver/installation/helm/powerflex.md PowerFlex changes are missing @francis-nijay

**Comment by francis-nijay** [comment]
> https://github.com/dell/csm-docs/blob/main/content/docs/csidriver/installation/helm/powerflex.md PowerFlex changes are missing @francis-nijay

Added now after discussion with powerflex team on multiple tags

**Review by shanmydell — APPROVED** [review]

**Review by ashish2207 — APPROVED** [review]

**Review by Sakshi-dell — APPROVED** [review]

**Review by harishp8889 — APPROVED** [review]

**Pull request merged**
